// <auto-generated />
namespace b2bSwgroup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class b2b13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(b2b13));
        
        string IMigrationMetadata.Id
        {
            get { return "201710111049127_b2b13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
